package model

type DouyinAutoGenerated struct {
	App struct {
		InitialState struct {
			RoomStore struct {
				RoomInfo struct {
					Room struct {
						IDStr        string `json:"id_str"`
						Status       int    `json:"status"`
						StatusStr    string `json:"status_str"`
						Title        string `json:"title"`
						UserCountStr string `json:"user_count_str"`
						Cover        struct {
							URLList []string `json:"url_list"`
						} `json:"cover"`
						StreamURL struct {
							FlvPullURL struct {
								FullHd1 string `json:"FULL_HD1"`
								Hd1     string `json:"HD1"`
								Sd1     string `json:"SD1"`
								Sd2     string `json:"SD2"`
							} `json:"flv_pull_url"`
							DefaultResolution string `json:"default_resolution"`
							HlsPullURLMap     struct {
								FullHd1 string `json:"FULL_HD1"`
								Hd1     string `json:"HD1"`
								Sd1     string `json:"SD1"`
								Sd2     string `json:"SD2"`
							} `json:"hls_pull_url_map"`
							HlsPullURL        string `json:"hls_pull_url"`
							StreamOrientation int    `json:"stream_orientation"`
							LiveCoreSdkData   struct {
								PullData struct {
									Options struct {
										DefaultQuality struct {
											Name       string `json:"name"`
											SdkKey     string `json:"sdk_key"`
											VCodec     string `json:"v_codec"`
											Resolution string `json:"resolution"`
											Level      int    `json:"level"`
										} `json:"default_quality"`
										Qualities []struct {
											Name       string `json:"name"`
											SdkKey     string `json:"sdk_key"`
											VCodec     string `json:"v_codec"`
											Resolution string `json:"resolution"`
											Level      int    `json:"level"`
										} `json:"qualities"`
									} `json:"options"`
									StreamData string `json:"stream_data"`
								} `json:"pull_data"`
							} `json:"live_core_sdk_data"`
						} `json:"stream_url"`
					} `json:"room"`
				} `json:"roomInfo"`
			} `json:"roomStore"`
		} `json:"initialState"`
	} `json:"app"`
}

type DouyinStreamData struct {
	Common struct {
		SessionID string `json:"session_id"`
		RuleIds   string `json:"rule_ids"`
	} `json:"common"`
	Data struct {
		Hd struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"hd"`
		Sd struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"sd"`
		Ld struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"ld"`
		Origin struct {
			Main struct {
				Flv       string `json:"flv"`
				Hls       string `json:"hls"`
				Cmaf      string `json:"cmaf"`
				Dash      string `json:"dash"`
				Lls       string `json:"lls"`
				Tsl       string `json:"tsl"`
				Tile      string `json:"tile"`
				SdkParams string `json:"sdk_params"`
			} `json:"main"`
		} `json:"origin"`
	} `json:"data"`
}
